language: clojure

services:
  - docker

before_script:
  - make install
  - sleep 15
  - docker ps -a
  - lein run </dev/null &
  - sleep 10

script:
- lein test
- lein doo chrome-headless test once


# https://github.com/cldwalker/datomic-box
# https://grishaev.me/en/pg-to-datomic/