language: clojure

services:
  - docker

before_script:
  - "make preparings-for-ci-tests-1"
  - sleep 10

script:
- lein test
- lein doo chrome-headless test once


# https://github.com/cldwalker/datomic-box
# https://grishaev.me/en/pg-to-datomic/