language: clojure

before_script:
  - "make preparings-for-ci-tests"
  - sleep 3

script:
- lein test
- lein doo chrome-headless test once


# https://github.com/cldwalker/datomic-box
# https://grishaev.me/en/pg-to-datomic/