FROM clojure:lein-2.9.1-alpine
# clojure

ARG DATOMIC_USERNAME
ARG DATOMIC_PASSWORD
ARG DATOMIC_VERSION

# MAINTAINER

ENV DATOMIC_HOME /opt/datomic-pro-$DATOMIC_VERSION
ENV DATOMIC_DATA $DATOMIC_HOME/data


RUN apk add --no-cache unzip curl


# ONBUILD RUN curl -u $(cat /tmp/.credentials) -SL https://my.datomic.com/repo/com/datomic/datomic-pro/$DATOMIC_VERSION/datomic-pro-$DATOMIC_VERSION.zip -o /tmp/datomic.zip \
#   && unzip /tmp/datomic.zip -d /opt \
#   && rm -f /tmp/datomic.zip

RUN curl -u $DATOMIC_USERNAME:$DATOMIC_PASSWORD -SL https://my.datomic.com/repo/com/datomic/datomic-pro/$DATOMIC_VERSION/datomic-pro-$DATOMIC_VERSION.zip -o /tmp/datomic.zip
RUN unzip /tmp/datomic.zip -d /opt
RUN rm -f /tmp/datomic.zip


# 2. Make sure to have a config/ folder in the same folder as your
# Dockerfile containing the transactor property file you wish to use
# ONBUILD 
ADD config $DATOMIC_HOME/config

WORKDIR $DATOMIC_HOME
RUN echo DATOMIC HOME: $DATOMIC_HOME
ENTRYPOINT ["./bin/transactor"]

# 3. Provide a CMD argument with the relative path to the
# transactor.properties file it will supplement the ENTRYPOINT
VOLUME $DATOMIC_DATA

EXPOSE 4334 4335 4336

CMD ["config/dev-transactor.properties"]
